"""
deploy.py — Azure ML deployment script for SAS → Python converter.
Auto-generated by the conversion pipeline.
"""
import os
import logging
from pathlib import Path
from datetime import datetime

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")


def main():
    from azure.identity import DefaultAzureCredential
    from azure.ai.ml import MLClient
    from azure.ai.ml.entities import (
        Model, Environment, ManagedOnlineEndpoint, ManagedOnlineDeployment, CodeConfiguration
    )
    from azure.ai.ml.constants import AssetTypes

    subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]
    resource_group  = os.environ["AZURE_RESOURCE_GROUP"]
    workspace_name  = os.environ["AZURE_ML_WORKSPACE"]

    credential = DefaultAzureCredential()
    ml_client  = MLClient(credential, subscription_id, resource_group, workspace_name)
    logger.info("Connected to workspace: %s", workspace_name)

    # ── Validate model.pkl ──────────────────────────────────────────────
    model_path = Path("output/report/model.pkl")
    if not model_path.exists():
        raise RuntimeError(f"model.pkl not found at {model_path.absolute()}. Run conversion first.")
    logger.info("Model found at: %s", model_path.absolute())

    # ── Register model ──────────────────────────────────────────────────
    model = ml_client.models.create_or_update(Model(
        path=str(model_path),
        name="code-converter-model",
        type=AssetTypes.CUSTOM_MODEL,
        tags={
            "source_language": "SAS",
            "target_language": "Python",
            "timestamp": datetime.utcnow().isoformat(),
        },
    ))
    logger.info("Registered model: %s (version %s)", model.name, model.version)

    # ── Create/update environment ───────────────────────────────────────
    env = ml_client.environments.create_or_update(Environment(
        name="code-converter-env",
        conda_file="output/converted_code/conda.yaml",
        image="mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04",
    ))
    logger.info("Environment: %s (version %s)", env.name, env.version)

    # ── Create endpoint (idempotent) ────────────────────────────────────
    endpoint_name = "code-converter-endpoint"
    try:
        ml_client.online_endpoints.get(endpoint_name)
        logger.info("Endpoint already exists: %s", endpoint_name)
    except Exception:
        ml_client.online_endpoints.begin_create_or_update(
            ManagedOnlineEndpoint(name=endpoint_name, auth_mode="key")
        ).result()
        logger.info("Created endpoint: %s", endpoint_name)

    # ── Create/update deployment ────────────────────────────────────────
    deployment = ml_client.online_deployments.begin_create_or_update(
        ManagedOnlineDeployment(
            name="blue",
            endpoint_name=endpoint_name,
            model=model.id,
            environment=env.id,
            code_configuration=CodeConfiguration(
                code="output/converted_code",
                scoring_script="score.py",
            ),
            instance_type="Standard_DS3_v2",
            instance_count=1,
        )
    ).result()
    logger.info("Deployment ready: %s", deployment.name)

    # ── Route 100% traffic ──────────────────────────────────────────────
    endpoint = ml_client.online_endpoints.get(endpoint_name)
    endpoint.traffic = {"blue": 100}
    ml_client.online_endpoints.begin_create_or_update(endpoint).result()
    logger.info("Traffic routed 100%% → blue")


if __name__ == "__main__":
    main()
