"""
score.py — Azure ML inference script for SAS → Python converter.
Auto-generated by the conversion pipeline.
"""
import os
import json
import logging
import joblib

logger = logging.getLogger(__name__)
_model = None


def init():
    global _model
    model_dir = os.environ.get("AZUREML_MODEL_DIR", ".")
    model_path = os.path.join(model_dir, "model.pkl")
    if not os.path.exists(model_path):
        model_path = "output/report/model.pkl"
    logger.info("Loading model from: %s", os.path.abspath(model_path))
    _model = joblib.load(model_path)
    logger.info("Model loaded successfully.")


def run(raw_data):
    try:
        data = json.loads(raw_data) if isinstance(raw_data, str) else raw_data
        code = data.get("code")
        source_lang = data.get("source_lang", "SAS")
        target_lang = data.get("target_lang", "Python")

        if not code:
            return json.dumps({"status": "error", "message": "Missing required field: code"})

        engine = _model.get("engine") if isinstance(_model, dict) else _model
        result = engine.convert_file.__func__(engine, code) if engine else None

        return json.dumps({
            "status": "success",
            "converted_code": getattr(result, "converted_code", ""),
            "source_lang": source_lang,
            "target_lang": target_lang,
        })
    except Exception as exc:
        logger.exception("Inference error: %s", exc)
        return json.dumps({"status": "error", "message": str(exc)})


if __name__ == "__main__":
    init()
    sample = json.dumps({"code": "x <- 1 + 1", "source_lang": "SAS", "target_lang": "Python"})
    print(run(sample))
